### PR TITLE
Release v0.2.1

### PR DESCRIPTION
**Pull request by rrey**
##### SUMMARY

Update galaxy.yml to release v0.2.1

### CODE REVIEW

**Comment by seuf** [comment]
The is no changelog between each relase ?

**Comment by rrey** [comment]
> The is no changelog between each relase ?

Ha ! Nice catch !

**Comment by gundalow** [comment]
Ping me once you'd like this pushed to Galaxy

**Comment by gundalow** [comment]
@rrey @seuf Great work as always.
Would you like me to publish `0.2.1` to Galaxy?

**Comment by rrey** [comment]
@gundalow yes that would be great !

**Comment by gundalow** [comment]
0.2.1 has been published to Galaxy. 
Excellent work everybody 

https://galaxy.ansible.com/community/grafana

**Pull request merged**
