### PR TITLE
Use module_utils doc fragment and argument_spec in grafana_user

### PR DESCRIPTION
**Pull request by rrey**
##### SUMMARY

The `grafana-user` module was not using the doc fragment and grafana_argument-spec

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
grafana_user.py

### CODE REVIEW

**Comment by rrey** [comment]
@gundalow ensile-minimal was archived, should be move to ansible-mintest or return to the public one ?

**Comment by gundalow** [comment]
Ah, yes, see my other PR

**Comment by gundalow** [comment]
I'm updating CI to use ansible-base in https://github.com/ansible-collections/grafana/pull/42

**Comment by gundalow** [comment]
Hopefully, a rebase should get CI passing.

**Comment by rrey** [comment]
Splitted the doc fragment to allow using partial fragments in modules.
The grafana_user module only supports basic_auth (because the api only supports this method) and we should be able to pull the basic auth doc fragment only.

**Comment by gundalow** [comment]
Wonder if https://github.com/ansible-collections/grafana/pull/43 will stop diff from failing CI.

**Pull request merged**
