### PR TITLE
Manage Grafana User

### PR DESCRIPTION
**Pull request by pomverte**
##### SUMMARY
Add a module to manage (create, update, delete) Grafana user

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
- grafana_user.py

##### ADDITIONAL INFORMATION
Sponsored by @rrey

### CODE REVIEW

**Comment by rrey** [comment]
@all-contributors add @pomverte for code and test

**Comment by rrey** [comment]
@all-contributors add @Tailzip @jual  for code and test

**Comment by rrey** [comment]
@all-contributors add @jual for code and test

**Comment by gundalow** [comment]
@all-contributors add @jual for code and test

**Comment by gundalow** [comment]
@all-contributors add @jual for code and test

**Comment by rrey** [comment]
@all-contributors add @MCyprien for code and test

**Pull request merged**
