### PR TITLE
Use codecov-action to upload Code Coverage report

### PR DESCRIPTION
**Pull request by geerlingguy**
Edit (to make `mergeable` bot happy): Use codecov-action to upload Code Coverage report

### CODE REVIEW

**Comment by geerlingguy** [comment]
Weird, it worked in the `units` action, but not in the `integration` action:

```
/usr/bin/docker exec  10f63301684e634ae2a7b144c3595484d89c07283ec8642cb36f6d08fe43ee82 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "no such file or directory": unknown
```

Maybe code coverage should only be uploaded from the units run?

**Comment by gundalow** [comment]
```
/usr/bin/docker exec  10f63301684e634ae2a7b144c3595484d89c07283ec8642cb36f6d08fe43ee82 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "no such file or directory": unknown
```
:(

**Comment by geerlingguy** [comment]
@gundalow trying again, only running coverage report on units scenario and not also on integration.

**Comment by rrey** [comment]
thank you @geerlingguy for doing this <3

**Pull request merged**
