### PR TITLE
dashboard: fix issue during import

### PR DESCRIPTION
**Pull request by rrey**
When testing dashboad payload between the test resulted in reverted values
leading to the dashboard not being updated when it should.

Closes: #76

### CODE REVIEW

**Comment by rrey** [comment]
@CWollinger did you face an issue with meta ? I didn't face any issue with 6.6.2 and there is a comment in the code from @seuf stating that meta is never in the payload.

**Comment by CWollinger** [comment]
@rrey Yes. When I query the API (/api/dashboards/uid/), I receive meta data. So the payload var also contain meta key.

Tested it with 6.5.3 and 6.6.2

**Comment by seuf** [comment]
LGTM

**Comment by rrey** [comment]
@CWollinger the `dashboard` variable is the dashboard retrieved from the API and the `meta` is removed line 280-281.
I'm gonna merge this patch, if you could test it and let me know if everything works that would be awesome.

**Comment by CWollinger** [comment]
@rrey the override after a change in the GUI works. But the changed check does not.
Now you update always the dashboard, also if there is no change. https://github.com/ansible-collections/grafana/blob/bbfce99732037a009919413731f5ebd1973fe548/plugins/modules/grafana_dashboard.py#L294

The `payload` var (exported db) contains the meta key (from the API).  Mentioned on the grafana site, too: https://grafana.com/docs/grafana/latest/http_api/dashboard/#get-dashboard-by-uid 
So `dashboard` dosn't contain meta but `payload` does (especially if you exported this db before).

**Comment by rrey** [comment]
Alright I’ll make the change asap

**Pull request merged**
